// ── Types ─────────────────────────────────────────────────────────────────────

export type MarketOutlook = "up" | "flat" | "down";
export type RecommendationStatus = "recommended" | "flagged";

export interface CareerMatch {
  id: string;
  title: string;
  sector: string;
  domain: string; // for domain filter
  matchPercent: number;
  status: RecommendationStatus;

  marketOutlookLabel: string;
  marketOutlook: MarketOutlook;

  salaryRange: string;
  salaryTier: 1 | 2 | 3 | 4;

  educationRequired: string;
  educationMatchesAnchor: boolean;

  keySynergy: string;
  keyFriction: string;

  pros: string[];
  cons: string[];

  flagReason?: string;
}

export interface ResultSet {
  id: string;
  label: string;
  confidencePercent: number;
  activeVariables: string;
  careers: CareerMatch[];
}

// ── Result Set 1 — Technology & Research ──────────────────────────────────────

const resultSet1: ResultSet = {
  id: "rs1",
  label: "Technology & Research",
  confidencePercent: 91,
  activeVariables: "INTJ-A, Remote, Master's anchor, 4 active variables",
  careers: [
    {
      id: "rs1-r1",
      title: "Data Scientist / ML Engineer",
      sector: "Technology",
      domain: "Technology",
      matchPercent: 96,
      status: "recommended",
      marketOutlookLabel: "High Growth (14% YoY)",
      marketOutlook: "up",
      salaryRange: "$115k – $170k",
      salaryTier: 4,
      educationRequired: "MS Preferred",
      educationMatchesAnchor: true,
      keySynergy: "Deep systems thinking perfectly matches ML model architecture work.",
      keyFriction: "Cross-team sprint cycles can disrupt deep-focus work blocks.",
      pros: [
        "Leverages pattern-recognition and analytical reasoning at the highest level.",
        "Fully remote roles are standard across the industry.",
        "High autonomy in research pipeline design and model selection.",
        "Measurable deliverables provide a strong sense of ongoing progress.",
        "Compensation ceiling is among the highest in any technical field.",
      ],
      cons: [
        "Occasional non-technical stakeholder presentations required.",
        "Agile sprint cadence can interrupt deep-focus work sessions.",
      ],
    },
    {
      id: "rs1-r2",
      title: "Quantitative Research Analyst",
      sector: "Finance / Research",
      domain: "Finance",
      matchPercent: 89,
      status: "recommended",
      marketOutlookLabel: "Stable (3% YoY)",
      marketOutlook: "flat",
      salaryRange: "$130k – $200k+",
      salaryTier: 4,
      educationRequired: "MS / PhD Preferred",
      educationMatchesAnchor: true,
      keySynergy: "Pure independent analytical work — zero people-management requirements.",
      keyFriction: "Regulatory filing cycles add bureaucratic overhead.",
      pros: [
        "Almost entirely solo work with minimal coordination overhead.",
        "Abstract, model-driven problem space ideal for intuitive thinkers.",
        "Compensation ceiling with performance bonuses is exceptionally high.",
        "Remote-first culture prevalent at quantitative hedge funds.",
        "Intellectual autonomy over methodology and tooling choices.",
      ],
      cons: [
        "Compliance documentation requirements can feel tedious.",
        "Market volatility introduces external unpredictability.",
      ],
    },
    {
      id: "rs1-r3",
      title: "Cybersecurity Architect",
      sector: "Technology",
      domain: "Technology",
      matchPercent: 85,
      status: "recommended",
      marketOutlookLabel: "Very High Growth (18% YoY)",
      marketOutlook: "up",
      salaryRange: "$130k – $180k",
      salaryTier: 4,
      educationRequired: "BS / MS Required",
      educationMatchesAnchor: true,
      keySynergy: "Strategic security design rewards long-horizon systems thinking.",
      keyFriction: "Incident response requires high-urgency context-switching.",
      pros: [
        "High-stakes strategic role with near-total technical autonomy.",
        "Critical shortage of qualified architects drives compensation premiums.",
        "Remote-friendly with deep independent research time.",
        "Work carries clear societal and organizational significance.",
        "Continuous intellectual challenge from evolving threat landscape.",
      ],
      cons: [
        "On-call incident response disrupts preferred deep-work schedules.",
        "Requires continuous credential maintenance (CISSP, etc.).",
      ],
    },
    {
      id: "rs1-r4",
      title: "AI Research Scientist",
      sector: "Technology / Academia",
      domain: "Technology",
      matchPercent: 83,
      status: "recommended",
      marketOutlookLabel: "High Growth (20%+ YoY)",
      marketOutlook: "up",
      salaryRange: "$140k – $250k",
      salaryTier: 4,
      educationRequired: "PhD Preferred",
      educationMatchesAnchor: false,
      keySynergy: "Pure research environment maximizes intellectual independence.",
      keyFriction: "PhD requirement is above current education anchor.",
      pros: [
        "Maximum intellectual freedom to pursue novel research directions.",
        "Collaboration limited to small, high-caliber peer groups.",
        "Remote and hybrid work widely available at top-tier labs.",
        "Work has direct long-term societal and technological impact.",
        "Publishing record builds compounding professional reputation.",
      ],
      cons: [
        "PhD requirement represents a significant additional investment.",
        "Publish-or-perish culture creates output pressure.",
      ],
    },
    {
      id: "rs1-r5",
      title: "Software Architect / Technical Lead",
      sector: "Technology",
      domain: "Technology",
      matchPercent: 79,
      status: "recommended",
      marketOutlookLabel: "Steady Growth (7% YoY)",
      marketOutlook: "up",
      salaryRange: "$140k – $210k",
      salaryTier: 4,
      educationRequired: "BS / MS Preferred",
      educationMatchesAnchor: true,
      keySynergy: "System design and architectural planning suits long-horizon strategic thinkers.",
      keyFriction: "Team leadership introduces regular interpersonal coordination.",
      pros: [
        "Deep technical ownership of high-complexity systems.",
        "Architecture work is largely independent with minimal micromanagement.",
        "Remote-first across most top tech employers.",
        "High compensation with significant equity upside at growth companies.",
        "Architectural decisions have measurable long-term organizational impact.",
      ],
      cons: [
        "Leadership component requires regular mentoring and team coordination.",
        "Meeting load increases significantly compared to individual contributor roles.",
      ],
    },
    {
      id: "rs1-f1",
      title: "Event Coordinator / Planner",
      sector: "Hospitality",
      domain: "Creative Arts",
      matchPercent: 8,
      status: "flagged",
      marketOutlookLabel: "Slow Growth (2% YoY)",
      marketOutlook: "flat",
      salaryRange: "$40k – $65k",
      salaryTier: 1,
      educationRequired: "BS / Certificate",
      educationMatchesAnchor: true,
      keySynergy: "Organizational skills could apply to logistics planning.",
      keyFriction: "Constant human interaction and in-person presence are core role requirements.",
      flagReason: "Severe mismatch. The role is fundamentally defined by high-volume social interaction, vendor negotiation, and on-site presence — all directly conflicting with introversion, remote preference, and deep-focus working style.",
      pros: ["Organizational skills transferable from structured planning."],
      cons: [
        "Requires constant high-energy social interaction.",
        "Entirely in-person role — no remote option exists.",
        "Success depends on charisma and improvisation under pressure.",
        "Low compensation ceiling relative to skills required.",
      ],
    },
    {
      id: "rs1-f2",
      title: "K-12 Classroom Teacher",
      sector: "Education",
      domain: "Education",
      matchPercent: 14,
      status: "flagged",
      marketOutlookLabel: "Moderate (3% YoY)",
      marketOutlook: "flat",
      salaryRange: "$38k – $65k",
      salaryTier: 1,
      educationRequired: "BS + Teaching Certificate",
      educationMatchesAnchor: true,
      keySynergy: "Deep subject mastery could enhance content delivery quality.",
      keyFriction: "Continuous classroom management and emotional labor conflicts with introversion.",
      flagReason: "Daily classroom management, behavioral intervention, and high-volume emotional labor are fundamentally incompatible with an introverted, structured-work profile. Remote work is not viable.",
      pros: ["Subject expertise is highly valued in specialized roles."],
      cons: [
        "Continuous classroom noise and emotional demands are draining.",
        "No remote option — requires daily in-person presence.",
        "Low compensation relative to education and skill level.",
        "Behavioral management creates unpredictable, high-friction workdays.",
      ],
    },
    {
      id: "rs1-f3",
      title: "Retail Store Manager",
      sector: "Retail",
      domain: "Business",
      matchPercent: 6,
      status: "flagged",
      marketOutlookLabel: "Declining (−2% YoY)",
      marketOutlook: "down",
      salaryRange: "$45k – $70k",
      salaryTier: 2,
      educationRequired: "HS / BS Preferred",
      educationMatchesAnchor: true,
      keySynergy: "Process optimization skills could improve store operations.",
      keyFriction: "High daily people-management, foot traffic, and in-person requirement.",
      flagReason: "Role demands constant customer-facing interaction, real-time conflict resolution, and full in-store presence — directly opposing remote preference, introversion, and preference for structured analytical work.",
      pros: ["Systems optimization skills could improve operational efficiency."],
      cons: [
        "Constant customer and staff interaction throughout the day.",
        "Entirely in-store — remote work categorically unavailable.",
        "High emotional labor and conflict-management requirements.",
        "Industry is structurally declining due to e-commerce displacement.",
      ],
    },
    {
      id: "rs1-f4",
      title: "Public Relations Specialist",
      sector: "Communications",
      domain: "Creative Arts",
      matchPercent: 11,
      status: "flagged",
      marketOutlookLabel: "Flat (1% YoY)",
      marketOutlook: "flat",
      salaryRange: "$55k – $90k",
      salaryTier: 2,
      educationRequired: "BS Required",
      educationMatchesAnchor: true,
      keySynergy: "Strong written communication could apply to media drafting.",
      keyFriction: "Media liaison, press conferences, and real-time crisis communication require high extroversion.",
      flagReason: "Core role competencies — rapid media response, public-facing communication, and relationship management — directly conflict with introversion and preference for structured, low-interruption work.",
      pros: ["Written communication strength transfers to press release drafting."],
      cons: [
        "Media crisis response requires always-on availability.",
        "Heavy relationship management and networking requirements.",
        "In-person press events and conferences are unavoidable.",
        "Reactive work pace conflicts with preference for planned, deep-focus output.",
      ],
    },
    {
      id: "rs1-f5",
      title: "Financial Advisor (Retail)",
      sector: "Finance",
      domain: "Finance",
      matchPercent: 18,
      status: "flagged",
      marketOutlookLabel: "Slow Growth (4% YoY)",
      marketOutlook: "flat",
      salaryRange: "$55k – $120k",
      salaryTier: 2,
      educationRequired: "BS + Series 65/66",
      educationMatchesAnchor: true,
      keySynergy: "Analytical investment research skills partially transferable.",
      keyFriction: "Client acquisition and retention requires high-touch relationship management incompatible with introversion.",
      flagReason: "Retail financial advising is fundamentally a relationship-selling role. Client acquisition through networking, cold outreach, and referral cultivation directly conflicts with introversion and preference for analytical, independent work.",
      pros: [
        "Quantitative analysis skills apply to portfolio construction.",
        "Income ceiling is high with a strong book of business.",
      ],
      cons: [
        "Client acquisition requires constant networking and cold outreach.",
        "Income is commission-dependent with high early-career uncertainty.",
        "Mandatory in-person client meetings conflict with remote preference.",
        "Success metrics are entirely relationship-based, not analytical.",
      ],
    },
  ],
};

// ── Result Set 2 — Law, Policy & Strategy ─────────────────────────────────────

const resultSet2: ResultSet = {
  id: "rs2",
  label: "Law, Policy & Strategy",
  confidencePercent: 85,
  activeVariables: "INTJ-A, Hybrid, Master's anchor, 5 active variables",
  careers: [
    {
      id: "rs2-r1",
      title: "Corporate Strategy Consultant",
      sector: "Consulting",
      domain: "Business",
      matchPercent: 92,
      status: "recommended",
      marketOutlookLabel: "High Growth (10% YoY)",
      marketOutlook: "up",
      salaryRange: "$120k – $200k",
      salaryTier: 4,
      educationRequired: "MBA / MS Preferred",
      educationMatchesAnchor: true,
      keySynergy: "Strategic systems analysis and long-range planning are core INTJ strengths.",
      keyFriction: "Client-facing presentations and travel requirements conflict with introversion.",
      pros: [
        "High-level strategic analysis with direct organizational impact.",
        "Work is intellectually diverse — new problems across different industries.",
        "Strong meritocratic advancement based on output quality.",
        "Top-tier compensation with performance bonuses.",
        "Remote engagements are increasingly common post-2020.",
      ],
      cons: [
        "Client presentations and stakeholder management require extroversion.",
        "Travel-heavy engagements can conflict with remote preference.",
      ],
    },
    {
      id: "rs2-r2",
      title: "Patent Attorney / IP Counsel",
      sector: "Law / Technology",
      domain: "Law",
      matchPercent: 87,
      status: "recommended",
      marketOutlookLabel: "Steady Growth (6% YoY)",
      marketOutlook: "up",
      salaryRange: "$130k – $190k",
      salaryTier: 4,
      educationRequired: "J.D. Required",
      educationMatchesAnchor: false,
      keySynergy: "Legal analysis and technical precision rewards structured analytical thinking.",
      keyFriction: "J.D. is above current education anchor — significant additional investment.",
      pros: [
        "Highly analytical work with clear logical frameworks.",
        "Significant independent research and writing time.",
        "Tech-sector specialization commands premium rates.",
        "Well-defined advancement track from associate to partner.",
        "Remote work is increasingly available for established practitioners.",
      ],
      cons: [
        "J.D. requires 3 additional years of education and significant debt.",
        "Billable-hour culture creates output pressure independent of quality.",
      ],
    },
    {
      id: "rs2-r3",
      title: "Policy Research Analyst",
      sector: "Government / Think Tank",
      domain: "Law",
      matchPercent: 82,
      status: "recommended",
      marketOutlookLabel: "Stable (2% YoY)",
      marketOutlook: "flat",
      salaryRange: "$65k – $95k",
      salaryTier: 2,
      educationRequired: "MS / MPA Preferred",
      educationMatchesAnchor: true,
      keySynergy: "Deep research and long-form analytical writing perfectly suits this profile.",
      keyFriction: "Compensation ceiling is significantly lower than private-sector equivalents.",
      pros: [
        "Deep independent research with direct public-policy impact.",
        "Long-form writing and analysis are the core deliverables.",
        "Government and NGO roles offer strong work-life stability.",
        "Hybrid and remote options widely available at think tanks.",
        "High sense of purpose from policy work with societal implications.",
      ],
      cons: [
        "Compensation is substantially below private-sector equivalents.",
        "Bureaucratic approval cycles slow the pace of meaningful output.",
      ],
    },
    {
      id: "rs2-r4",
      title: "Compliance Officer / Risk Analyst",
      sector: "Finance / Legal",
      domain: "Finance",
      matchPercent: 78,
      status: "recommended",
      marketOutlookLabel: "Growing (8% YoY)",
      marketOutlook: "up",
      salaryRange: "$85k – $140k",
      salaryTier: 3,
      educationRequired: "BS / MS Required",
      educationMatchesAnchor: true,
      keySynergy: "Systematic rule-based analysis and risk modeling suits Judging-dominant profiles.",
      keyFriction: "Cross-departmental liaison work requires regular interpersonal coordination.",
      pros: [
        "Highly structured, rules-based work environment.",
        "Strong demand as regulatory complexity increases globally.",
        "Independent analytical work with minimal team dependencies.",
        "Remote-compatible with most compliance frameworks.",
        "Clear career track to Chief Risk Officer or General Counsel.",
      ],
      cons: [
        "Cross-departmental liaison work requires regular communication.",
        "Regulatory changes can render specialized knowledge obsolete.",
      ],
    },
    {
      id: "rs2-r5",
      title: "Business Intelligence Analyst",
      sector: "Technology / Business",
      domain: "Business",
      matchPercent: 76,
      status: "recommended",
      marketOutlookLabel: "High Growth (11% YoY)",
      marketOutlook: "up",
      salaryRange: "$85k – $135k",
      salaryTier: 3,
      educationRequired: "BS / MS Preferred",
      educationMatchesAnchor: true,
      keySynergy: "Converting raw data into strategic organizational insights suits analytical precision.",
      keyFriction: "Stakeholder dashboard reviews require regular communication cycles.",
      pros: [
        "Translates data into strategic decisions — high organizational visibility.",
        "Largely independent analytical work with defined deliverable cycles.",
        "Remote-compatible across virtually all industries.",
        "High demand across every sector creating strong job security.",
        "Clear tooling mastery (SQL, Tableau, Power BI) enables rapid skill-building.",
      ],
      cons: [
        "Regular dashboard review meetings with business stakeholders.",
        "Work is often reactive to business questions rather than self-directed.",
      ],
    },
    {
      id: "rs2-f1",
      title: "Real Estate Agent",
      sector: "Real Estate",
      domain: "Business",
      matchPercent: 7,
      status: "flagged",
      marketOutlookLabel: "Volatile Market",
      marketOutlook: "down",
      salaryRange: "$40k – $100k (commission)",
      salaryTier: 2,
      educationRequired: "License Required",
      educationMatchesAnchor: true,
      keySynergy: "Market analysis could inform property valuation work.",
      keyFriction: "Income entirely dependent on client relationship cultivation and in-person showings.",
      flagReason: "Fundamentally a high-extroversion relationship sales role. Success depends entirely on network cultivation, open houses, and client emotional management — all directly incompatible with introversion and remote preference.",
      pros: ["Market research skills apply to property valuation."],
      cons: [
        "100% commission income creates high financial uncertainty.",
        "Constant in-person client interaction and property showings.",
        "Networking and cold prospecting are core daily activities.",
        "Entirely dependent on interpersonal trust-building.",
      ],
    },
    {
      id: "rs2-f2",
      title: "Insurance Sales Agent",
      sector: "Insurance",
      domain: "Finance",
      matchPercent: 9,
      status: "flagged",
      marketOutlookLabel: "Stable (3% YoY)",
      marketOutlook: "flat",
      salaryRange: "$45k – $85k",
      salaryTier: 2,
      educationRequired: "HS / BS + License",
      educationMatchesAnchor: true,
      keySynergy: "Analytical policy comparison could assist product knowledge.",
      keyFriction: "Cold prospecting, rejection tolerance, and emotional persuasion are core role requirements.",
      flagReason: "Pure sales role dependent on high-frequency cold outreach, rejection management, and emotional persuasion techniques — directly opposing analytical, introversion-dominant profiles.",
      pros: ["Policy comparison requires structured analytical thinking."],
      cons: [
        "Cold calling and prospecting are the primary daily activity.",
        "Compensation tied entirely to sales performance.",
        "High rejection rate creates chronic emotional stress for introverts.",
        "In-person meetings are standard practice.",
      ],
    },
    {
      id: "rs2-f3",
      title: "Social Worker",
      sector: "Social Services",
      domain: "Education",
      matchPercent: 13,
      status: "flagged",
      marketOutlookLabel: "Growing (9% YoY)",
      marketOutlook: "up",
      salaryRange: "$42k – $65k",
      salaryTier: 1,
      educationRequired: "MSW Required",
      educationMatchesAnchor: true,
      keySynergy: "Systemic thinking could inform program design.",
      keyFriction: "High emotional labor, in-person client engagement, and crisis intervention required daily.",
      flagReason: "The role demands sustained emotional availability, crisis management, and high-volume client interaction — profoundly draining for thinking-dominant, introverted profiles. Compensation is also substantially below skills market rate.",
      pros: ["Systems analysis applies to program and policy design."],
      cons: [
        "Sustained emotional labor leads to high burnout risk.",
        "Daily in-person crisis intervention is unavoidable.",
        "Compensation is severely below market for the required MSW credential.",
        "Work context is emotionally heavy and structurally unpredictable.",
      ],
    },
    {
      id: "rs2-f4",
      title: "Flight Attendant",
      sector: "Aviation",
      domain: "Creative Arts",
      matchPercent: 4,
      status: "flagged",
      marketOutlookLabel: "Recovering (5% YoY)",
      marketOutlook: "up",
      salaryRange: "$40k – $70k",
      salaryTier: 1,
      educationRequired: "HS Diploma",
      educationMatchesAnchor: true,
      keySynergy: "Crisis protocol adherence aligns with structured rule-following preferences.",
      keyFriction: "Constant public-facing interaction, irregular hours, and no remote option.",
      flagReason: "Completely incompatible profile. Role requires constant public-facing service, irregular shift work, and zero remote possibility — opposing every key preference signal including introversion, remote work, and education-level anchoring.",
      pros: ["Emergency protocol adherence suits structured rule-following."],
      cons: [
        "Constant passenger interaction throughout every shift.",
        "Irregular schedules and frequent travel disrupt routine.",
        "Entirely in-person — remote work categorically unavailable.",
        "Significant credential underutilization relative to education level.",
      ],
    },
    {
      id: "rs2-f5",
      title: "Political Campaign Manager",
      sector: "Politics",
      domain: "Law",
      matchPercent: 10,
      status: "flagged",
      marketOutlookLabel: "Cyclical (election-dependent)",
      marketOutlook: "flat",
      salaryRange: "$50k – $100k",
      salaryTier: 2,
      educationRequired: "BS Preferred",
      educationMatchesAnchor: true,
      keySynergy: "Strategic planning skills partially applicable to campaign logistics.",
      keyFriction: "Chaotic, always-on environment with constant stakeholder and media management.",
      flagReason: "Role demands 24/7 availability during campaign cycles, media management, and high-frequency stakeholder communication — antithetical to deep-work, structured, and introversion-dominant profiles.",
      pros: ["Strategic planning skills apply to campaign logistics design."],
      cons: [
        "Always-on availability during campaign cycles.",
        "Constant media, donor, and candidate management.",
        "Entirely cyclical income with no job security between cycles.",
        "High emotional volatility and unpredictable work conditions.",
      ],
    },
  ],
};

// ── Result Set 3 — Healthcare & Life Sciences ──────────────────────────────────

const resultSet3: ResultSet = {
  id: "rs3",
  label: "Healthcare & Life Sciences",
  confidencePercent: 83,
  activeVariables: "INFJ-T, Hybrid, Master's anchor, 4 active variables",
  careers: [
    {
      id: "rs3-r1",
      title: "Biomedical Research Scientist",
      sector: "Healthcare / Research",
      domain: "Medical",
      matchPercent: 93,
      status: "recommended",
      marketOutlookLabel: "High Growth (12% YoY)",
      marketOutlook: "up",
      salaryRange: "$90k – $140k",
      salaryTier: 3,
      educationRequired: "PhD / MS Required",
      educationMatchesAnchor: false,
      keySynergy: "Independent lab research suits deep-focus, hypothesis-driven analytical profiles.",
      keyFriction: "Grant writing and publication cycles create administrative burden.",
      pros: [
        "Deep independent research with direct impact on human health outcomes.",
        "Lab-based work is inherently structured and low social overhead.",
        "Publishing record builds long-term compounding career equity.",
        "Hybrid models increasingly common at research hospitals and biotech firms.",
        "High sense of purpose aligned with values-driven profiles.",
      ],
      cons: [
        "Grant writing and funding cycles create significant administrative burden.",
        "PhD requirement is above current education anchor.",
      ],
    },
    {
      id: "rs3-r2",
      title: "Health Informatics Specialist",
      sector: "Healthcare / Technology",
      domain: "Medical",
      matchPercent: 88,
      status: "recommended",
      marketOutlookLabel: "Very High Growth (17% YoY)",
      marketOutlook: "up",
      salaryRange: "$90k – $130k",
      salaryTier: 3,
      educationRequired: "MS Preferred",
      educationMatchesAnchor: true,
      keySynergy: "Bridges technical systems and healthcare data — ideal for analytical-empathic profiles.",
      keyFriction: "Cross-department implementation work requires regular stakeholder coordination.",
      pros: [
        "Intersects technical rigor with meaningful healthcare impact.",
        "Largely independent data systems work.",
        "Remote-compatible roles widely available.",
        "High demand across hospital systems, insurers, and government agencies.",
        "Clear career path to Chief Health Informatics Officer.",
      ],
      cons: [
        "EHR implementation projects require cross-departmental coordination.",
        "Healthcare bureaucracy slows technical improvement cycles.",
      ],
    },
    {
      id: "rs3-r3",
      title: "Pharmaceutical Regulatory Affairs Specialist",
      sector: "Pharmaceuticals",
      domain: "Medical",
      matchPercent: 84,
      status: "recommended",
      marketOutlookLabel: "Steady Growth (7% YoY)",
      marketOutlook: "up",
      salaryRange: "$85k – $130k",
      salaryTier: 3,
      educationRequired: "MS / PharmD Preferred",
      educationMatchesAnchor: true,
      keySynergy: "Rule-based regulatory interpretation rewards precision and structured analytical thinking.",
      keyFriction: "Inter-agency coordination requires regular written and verbal communication.",
      pros: [
        "Highly structured, rules-based environment with clear compliance frameworks.",
        "Independent document preparation and review are core deliverables.",
        "Remote-compatible for most document submission workflows.",
        "Strong demand as regulatory frameworks expand globally.",
        "Clear advancement path to Vice President of Regulatory Affairs.",
      ],
      cons: [
        "Inter-agency communication and FDA/EMA liaison work required.",
        "Submission deadlines create periodic high-pressure cycles.",
      ],
    },
    {
      id: "rs3-r4",
      title: "Clinical Data Analyst",
      sector: "Healthcare / Research",
      domain: "Medical",
      matchPercent: 81,
      status: "recommended",
      marketOutlookLabel: "High Growth (14% YoY)",
      marketOutlook: "up",
      salaryRange: "$75k – $115k",
      salaryTier: 3,
      educationRequired: "BS / MS Preferred",
      educationMatchesAnchor: true,
      keySynergy: "Statistical trial data analysis rewards precision and pattern-recognition strengths.",
      keyFriction: "Clinical team liaison work introduces interpersonal coordination requirements.",
      pros: [
        "Statistical analysis and data validation are core independent deliverables.",
        "Work directly contributes to drug approval and patient safety.",
        "Remote-first roles increasingly available in CRO sector.",
        "High demand across pharma, biotech, and hospital systems.",
        "Clear skill development path toward biostatistician or data science roles.",
      ],
      cons: [
        "Clinical team liaising requires regular structured communication.",
        "Regulatory documentation is highly repetitive.",
      ],
    },
    {
      id: "rs3-r5",
      title: "Epidemiologist / Public Health Researcher",
      sector: "Public Health",
      domain: "Medical",
      matchPercent: 77,
      status: "recommended",
      marketOutlookLabel: "High Growth (13% YoY)",
      marketOutlook: "up",
      salaryRange: "$70k – $110k",
      salaryTier: 2,
      educationRequired: "MPH / PhD Preferred",
      educationMatchesAnchor: false,
      keySynergy: "Population-level pattern detection and causal inference suits analytical depth profiles.",
      keyFriction: "Field work and community engagement may conflict with low-interaction preference.",
      pros: [
        "High-impact research with clear societal benefit.",
        "Primarily independent data analysis and modeling.",
        "Remote-compatible for data-heavy research phases.",
        "Published research builds lasting professional authority.",
        "Strong sense of purpose from disease prevention mission.",
      ],
      cons: [
        "Field work and community engagement sometimes required.",
        "Government and academic funding creates income uncertainty.",
      ],
    },
    {
      id: "rs3-f1",
      title: "Emergency Room Physician",
      sector: "Healthcare",
      domain: "Medical",
      matchPercent: 22,
      status: "flagged",
      marketOutlookLabel: "Stable (4% YoY)",
      marketOutlook: "flat",
      salaryRange: "$280k – $350k",
      salaryTier: 4,
      educationRequired: "MD + Residency",
      educationMatchesAnchor: false,
      keySynergy: "High compensation and diagnostic problem-solving have some alignment.",
      keyFriction: "Chaotic, high-noise environment with constant patient interaction and no remote option.",
      flagReason: "Despite strong compensation, the ER environment is the antithesis of a structured, low-interruption working preference. Constant patient interaction, unpredictable emergencies, and shift-based in-person requirements are incompatible.",
      pros: [
        "Diagnostic puzzle-solving engages analytical reasoning.",
        "Very high compensation ceiling.",
      ],
      cons: [
        "Constant high-noise, high-interruption environment.",
        "Entirely in-person with shift-based scheduling.",
        "MD + residency requires 8–12 years of additional education.",
        "Emotional burden of trauma cases creates chronic stress risk.",
      ],
    },
    {
      id: "rs3-f2",
      title: "Medical Sales Representative",
      sector: "Pharmaceuticals",
      domain: "Medical",
      matchPercent: 8,
      status: "flagged",
      marketOutlookLabel: "Declining (−1% YoY)",
      marketOutlook: "down",
      salaryRange: "$70k – $120k",
      salaryTier: 3,
      educationRequired: "BS Required",
      educationMatchesAnchor: true,
      keySynergy: "Product knowledge could leverage analytical background.",
      keyFriction: "Role is entirely defined by high-frequency in-person sales calls and relationship cultivation.",
      flagReason: "Pure sales role dependent on in-person physician visits, constant relationship management, and performance-based income. Directly conflicts with introversion, remote preference, and preference for analytical independent work.",
      pros: ["Technical product knowledge leverages science background."],
      cons: [
        "Daily in-person physician visits are the core job function.",
        "Constant relationship cultivation and cold calling required.",
        "Commission-dependent income creates financial instability.",
        "Industry is structurally declining due to digital channel shifts.",
      ],
    },
    {
      id: "rs3-f3",
      title: "Physical Therapist",
      sector: "Healthcare",
      domain: "Medical",
      matchPercent: 16,
      status: "flagged",
      marketOutlookLabel: "Growing (18% YoY)",
      marketOutlook: "up",
      salaryRange: "$75k – $100k",
      salaryTier: 2,
      educationRequired: "DPT Required",
      educationMatchesAnchor: false,
      keySynergy: "Structured treatment protocols suit rule-following precision.",
      keyFriction: "Constant in-person patient interaction and physical activity are unavoidable.",
      flagReason: "Full-time in-person patient care with physical activity requirements, constant interpersonal engagement, and no remote option. DPT also exceeds current education anchor.",
      pros: ["Structured protocol adherence rewards precision."],
      cons: [
        "100% in-person — remote work categorically unavailable.",
        "Constant patient interaction throughout every working day.",
        "DPT requires additional graduate education.",
        "Physical component may not align with preferred work style.",
      ],
    },
    {
      id: "rs3-f4",
      title: "Hospital Administrator",
      sector: "Healthcare Management",
      domain: "Medical",
      matchPercent: 19,
      status: "flagged",
      marketOutlookLabel: "Growing (9% YoY)",
      marketOutlook: "up",
      salaryRange: "$90k – $160k",
      salaryTier: 3,
      educationRequired: "MHA / MBA Required",
      educationMatchesAnchor: true,
      keySynergy: "Organizational systems optimization partially aligns with strategic thinking.",
      keyFriction: "High-volume interdepartmental meetings, staff management, and crisis escalation are daily requirements.",
      flagReason: "Administrative hospital leadership demands constant interdepartmental coordination, crisis escalation management, and high-frequency staff engagement — directly conflicting with deep-focus and introversion-dominant profiles.",
      pros: ["Systems optimization work has strategic and analytical components."],
      cons: [
        "Constant staff management and interdepartmental meetings.",
        "Crisis escalation and conflict resolution are regular requirements.",
        "Largely in-person role tied to the physical hospital campus.",
        "High administrative overhead with limited independent analysis time.",
      ],
    },
    {
      id: "rs3-f5",
      title: "Nursing Home Activities Director",
      sector: "Elder Care",
      domain: "Medical",
      matchPercent: 5,
      status: "flagged",
      marketOutlookLabel: "Growing (11% YoY)",
      marketOutlook: "up",
      salaryRange: "$38k – $55k",
      salaryTier: 1,
      educationRequired: "BS / Certificate",
      educationMatchesAnchor: true,
      keySynergy: "Program planning has organizational structure components.",
      keyFriction: "Daily high-touch resident engagement, entirely in-person, and low compensation.",
      flagReason: "Role requires daily high-energy social programming, emotional labor with vulnerable populations, and full in-person presence — incompatible across all key preference dimensions.",
      pros: ["Event planning component has organizational structure."],
      cons: [
        "Daily high-touch emotional engagement with residents.",
        "100% in-person with no remote possibility.",
        "Severe compensation ceiling given skills and credentials.",
        "Emotionally heavy role with high burnout risk.",
      ],
    },
  ],
};

// ── Result Set 4 — Creative Arts & Design ────────────────────────────────────

const resultSet4: ResultSet = {
  id: "rs4",
  label: "Creative Arts & Design",
  confidencePercent: 78,
  activeVariables: "ENFP-A, Hybrid, Bachelor's anchor, 3 active variables",
  careers: [
    {
      id: "rs4-r1",
      title: "UX Designer / Product Designer",
      sector: "Technology / Design",
      domain: "Creative Arts",
      matchPercent: 94,
      status: "recommended",
      marketOutlookLabel: "High Growth (13% YoY)",
      marketOutlook: "up",
      salaryRange: "$95k – $160k",
      salaryTier: 4,
      educationRequired: "BS / Portfolio Required",
      educationMatchesAnchor: true,
      keySynergy: "Human-centered design channels empathy and ideation into concrete product outcomes.",
      keyFriction: "Iterative stakeholder review cycles require regular presentation and feedback loops.",
      pros: [
        "Empathy and user-focused thinking are core job competencies.",
        "High creative latitude in interaction design and user flows.",
        "Remote-first roles standard across most tech companies.",
        "Strong compensation with equity upside at growth companies.",
        "Portfolio-based advancement — skills speak directly for themselves.",
      ],
      cons: [
        "Regular design review presentations to cross-functional stakeholders.",
        "Structured design system constraints can limit pure creative expression.",
      ],
    },
    {
      id: "rs4-r2",
      title: "Brand Strategist / Creative Director",
      sector: "Marketing / Creative",
      domain: "Creative Arts",
      matchPercent: 88,
      status: "recommended",
      marketOutlookLabel: "Stable Growth (6% YoY)",
      marketOutlook: "up",
      salaryRange: "$100k – $180k",
      salaryTier: 3,
      educationRequired: "BS / Portfolio Required",
      educationMatchesAnchor: true,
      keySynergy: "Big-picture conceptual thinking and storytelling are natural strengths.",
      keyFriction: "Client revision cycles and budget management require structured execution discipline.",
      pros: [
        "Conceptual vision work is the primary deliverable — not execution detail.",
        "Diverse client roster prevents intellectual stagnation.",
        "Strong sense of purpose when brand aligns with values.",
        "Hybrid and remote common across agencies and in-house teams.",
        "Creative leadership grows reputation as a compounding career asset.",
      ],
      cons: [
        "Client revision loops slow creative momentum.",
        "Budget management and vendor coordination require disciplined execution.",
      ],
    },
    {
      id: "rs4-r3",
      title: "Copywriter / Content Strategist",
      sector: "Marketing / Media",
      domain: "Creative Arts",
      matchPercent: 84,
      status: "recommended",
      marketOutlookLabel: "Moderate Growth (5% YoY)",
      marketOutlook: "up",
      salaryRange: "$60k – $110k",
      salaryTier: 2,
      educationRequired: "BS / Portfolio",
      educationMatchesAnchor: true,
      keySynergy: "Language, narrative, and conceptual framing are natural profile strengths.",
      keyFriction: "High-volume production briefs can feel repetitive and creativity-draining.",
      pros: [
        "Writing-first role with high creative independence.",
        "Fully remote across the vast majority of roles.",
        "Rapid skill development through high project volume.",
        "Freelance paths provide full schedule autonomy.",
        "Portfolio-driven advancement rewards quality over credentials.",
      ],
      cons: [
        "High-volume content briefs can feel formulaic and repetitive.",
        "Income ceiling is lower than design or strategy roles.",
      ],
    },
    {
      id: "rs4-r4",
      title: "Art Director / Visual Creative Director",
      sector: "Media / Advertising",
      domain: "Creative Arts",
      matchPercent: 81,
      status: "recommended",
      marketOutlookLabel: "Stable (3% YoY)",
      marketOutlook: "flat",
      salaryRange: "$80k – $150k",
      salaryTier: 3,
      educationRequired: "BFA / BS Required",
      educationMatchesAnchor: true,
      keySynergy: "Visual concept direction rewards strong aesthetic vision and big-picture thinking.",
      keyFriction: "Agency culture often requires in-person collaboration and client pitch presentations.",
      pros: [
        "Visual creative leadership with significant conceptual autonomy.",
        "Direct impact on brand perception across wide audiences.",
        "Portfolio-first advancement independent of academic pedigree.",
        "Hybrid models increasingly available at leading agencies.",
        "Creative prestige and industry recognition are meaningful career rewards.",
      ],
      cons: [
        "Client pitch presentations and brainstorm sessions require in-person energy.",
        "Agency deadlines create high-stress, compressed delivery cycles.",
      ],
    },
    {
      id: "rs4-r5",
      title: "Game Designer / Narrative Designer",
      sector: "Gaming / Interactive Media",
      domain: "Technology",
      matchPercent: 78,
      status: "recommended",
      marketOutlookLabel: "High Growth (10% YoY)",
      marketOutlook: "up",
      salaryRange: "$70k – $130k",
      salaryTier: 3,
      educationRequired: "BS / Portfolio Required",
      educationMatchesAnchor: true,
      keySynergy: "World-building, systems design, and narrative logic reward deep creative intuition.",
      keyFriction: "Crunch culture during release windows is a known industry challenge.",
      pros: [
        "Deep creative ownership of game systems and narrative structure.",
        "Remote-first culture has expanded significantly across studios.",
        "Intrinsically motivating work for individuals passionate about interactive media.",
        "Cross-disciplinary skills in writing, systems, and player psychology.",
        "Growing indie and AA studio market reduces AAA dependence.",
      ],
      cons: [
        "Crunch culture during game release windows is a structural industry issue.",
        "Entry-level pipeline is competitive with a high candidate-to-role ratio.",
      ],
    },
    {
      id: "rs4-f1",
      title: "Debt Collector",
      sector: "Finance / Collections",
      domain: "Finance",
      matchPercent: 3,
      status: "flagged",
      marketOutlookLabel: "Declining (−4% YoY)",
      marketOutlook: "down",
      salaryRange: "$35k – $50k",
      salaryTier: 1,
      educationRequired: "HS Diploma",
      educationMatchesAnchor: true,
      keySynergy: "None identified.",
      keyFriction: "High-conflict interpersonal interaction, rejection, and emotional drain are the core job experience.",
      flagReason: "Severe mismatch. Role consists entirely of high-conflict phone interactions with hostile counterparts, requiring constant emotional resilience to adversarial dialogue. Directly conflicts with every preference dimension.",
      pros: ["Entry-level access requires no credentials."],
      cons: [
        "Constant high-conflict phone calls with resistant counterparts.",
        "Emotionally exhausting work with high burnout rates.",
        "Structurally declining industry due to automation.",
        "Severe compensation floor with negligible advancement ceiling.",
      ],
    },
    {
      id: "rs4-f2",
      title: "Telemarketer",
      sector: "Sales",
      domain: "Business",
      matchPercent: 2,
      status: "flagged",
      marketOutlookLabel: "Rapidly Declining (−8% YoY)",
      marketOutlook: "down",
      salaryRange: "$28k – $42k",
      salaryTier: 1,
      educationRequired: "HS Diploma",
      educationMatchesAnchor: true,
      keySynergy: "None identified.",
      keyFriction: "Repetitive cold-call scripting, rejection loops, and compliance scripting directly conflict with every profile dimension.",
      flagReason: "Complete mismatch across all dimensions. Repetitive scripted cold calling, constant rejection, and severe automation-driven job decline make this role incompatible at every level of analysis.",
      pros: ["None identified that are relevant to this profile."],
      cons: [
        "Entirely repetitive scripted cold-call work.",
        "Highest rejection rates of any profession.",
        "Structurally collapsing industry due to AI and robocall automation.",
        "Severe compensation floor with no meaningful advancement.",
      ],
    },
    {
      id: "rs4-f3",
      title: "Construction Site Manager",
      sector: "Construction",
      domain: "Technology",
      matchPercent: 10,
      status: "flagged",
      marketOutlookLabel: "Moderate Growth (6% YoY)",
      marketOutlook: "up",
      salaryRange: "$75k – $110k",
      salaryTier: 2,
      educationRequired: "BS / Certification Required",
      educationMatchesAnchor: true,
      keySynergy: "Project logistics coordination aligns partially with structural planning tendencies.",
      keyFriction: "Outdoor physical presence, crew management, and uncontrolled environment conflict with all preference signals.",
      flagReason: "Full-time outdoor physical presence, constant subcontractor coordination, and weather-variable uncontrolled environments are incompatible with remote preference, introversion, and aversion to outdoor physical labor.",
      pros: ["Project management structure has some analytical components."],
      cons: [
        "100% outdoor in-person — remote work unavailable.",
        "Constant subcontractor management throughout every day.",
        "Physically demanding and weather-dependent working conditions.",
        "Stress is high and unpredictable due to site variables.",
      ],
    },
    {
      id: "rs4-f4",
      title: "Stand-Up Comedian",
      sector: "Entertainment",
      domain: "Creative Arts",
      matchPercent: 12,
      status: "flagged",
      marketOutlookLabel: "Highly Volatile",
      marketOutlook: "flat",
      salaryRange: "$20k – $500k+ (highly variable)",
      salaryTier: 1,
      educationRequired: "None Required",
      educationMatchesAnchor: true,
      keySynergy: "Observational pattern recognition has mild creative application.",
      keyFriction: "Public performance, social reading of live audiences, and constant rejection define the role.",
      flagReason: "Live performance-dependent role requiring constant public presence, high extroversion, audience reading, and extreme income volatility. Directly conflicts with introversion, structured work preference, and stable income requirements.",
      pros: ["Observational humor leverages pattern recognition."],
      cons: [
        "Entirely performance-based with extreme income volatility.",
        "Constant in-person performance and audience interaction.",
        "Career success requires an exceptionally high public persona.",
        "No remote option — live performance is the core product.",
      ],
    },
    {
      id: "rs4-f5",
      title: "Cruise Ship Entertainment Director",
      sector: "Hospitality",
      domain: "Creative Arts",
      matchPercent: 4,
      status: "flagged",
      marketOutlookLabel: "Recovering (7% YoY)",
      marketOutlook: "up",
      salaryRange: "$45k – $70k",
      salaryTier: 1,
      educationRequired: "BS / Hospitality Certificate",
      educationMatchesAnchor: true,
      keySynergy: "Event programming has logistical planning components.",
      keyFriction: "24/7 passenger-facing presence, at-sea isolation, and constant social energy expenditure.",
      flagReason: "Role requires 24/7 high-energy social programming for large passenger groups, at-sea geographic isolation, and continuous extroversion expenditure — incompatible with every key profile preference.",
      pros: ["Event logistics has organizational planning components."],
      cons: [
        "24/7 passenger-facing social programming is the job.",
        "At-sea isolation eliminates remote work entirely.",
        "Continuous extroversion expenditure causes rapid burnout for introverts.",
        "Compensation below market relative to hours and conditions.",
      ],
    },
  ],
};

// ── Result Set 5 — Education & Social Sciences ────────────────────────────────

const resultSet5: ResultSet = {
  id: "rs5",
  label: "Education & Social Sciences",
  confidencePercent: 80,
  activeVariables: "INFJ-A, Remote, Bachelor's anchor, 3 active variables",
  careers: [
    {
      id: "rs5-r1",
      title: "Instructional Designer / E-Learning Developer",
      sector: "Education Technology",
      domain: "Education",
      matchPercent: 91,
      status: "recommended",
      marketOutlookLabel: "High Growth (15% YoY)",
      marketOutlook: "up",
      salaryRange: "$70k – $115k",
      salaryTier: 3,
      educationRequired: "BS / MS Preferred",
      educationMatchesAnchor: true,
      keySynergy: "Systems thinking and curriculum architecture reward analytical depth and empathic design.",
      keyFriction: "Subject-matter expert coordination requires regular communication cycles.",
      pros: [
        "Independent curriculum architecture with high creative latitude.",
        "Fully remote roles are standard across the industry.",
        "Strong demand from corporate learning, higher education, and government.",
        "Work has clear and measurable learner impact.",
        "Diverse domain exposure prevents intellectual stagnation.",
      ],
      cons: [
        "SME coordination cycles require regular structured communication.",
        "Production timelines can compress creative development time.",
      ],
    },
    {
      id: "rs5-r2",
      title: "Organizational Psychologist / I-O Psychologist",
      sector: "Business / Psychology",
      domain: "Education",
      matchPercent: 87,
      status: "recommended",
      marketOutlookLabel: "Growing (8% YoY)",
      marketOutlook: "up",
      salaryRange: "$90k – $140k",
      salaryTier: 3,
      educationRequired: "MS / PhD Required",
      educationMatchesAnchor: false,
      keySynergy: "Behavioral systems analysis and organizational design align with deep pattern-recognition strengths.",
      keyFriction: "Consulting and workshop delivery require in-person client engagement.",
      pros: [
        "Applied human behavioral research with measurable organizational impact.",
        "Independent research and report preparation are core deliverables.",
        "Remote roles widely available for assessment and research functions.",
        "Highly valued specialization with limited practitioner supply.",
        "Work produces durable published outputs that compound in value.",
      ],
      cons: [
        "Consulting engagements require periodic in-person workshop delivery.",
        "PhD requirement represents a significant additional investment.",
      ],
    },
    {
      id: "rs5-r3",
      title: "University Professor / Academic Researcher",
      sector: "Higher Education",
      domain: "Education",
      matchPercent: 83,
      status: "recommended",
      marketOutlookLabel: "Stable (2% YoY)",
      marketOutlook: "flat",
      salaryRange: "$75k – $130k",
      salaryTier: 3,
      educationRequired: "PhD Required",
      educationMatchesAnchor: false,
      keySynergy: "Deep research autonomy and structured semester cycles suit long-horizon thinkers.",
      keyFriction: "PhD requirement and academic job market competition create significant entry barriers.",
      pros: [
        "Maximum research autonomy with full intellectual ownership.",
        "Tenure track provides long-term job security.",
        "Teaching is structured and bounded — not constant social interaction.",
        "Published work builds lasting intellectual legacy.",
        "Flexible schedule structure rewards disciplined independent workers.",
      ],
      cons: [
        "PhD track requires 4–6 years of additional investment.",
        "Academic job market is extremely competitive with high supply-demand mismatch.",
      ],
    },
    {
      id: "rs5-r4",
      title: "UX Researcher / Human Factors Specialist",
      sector: "Technology / Research",
      domain: "Technology",
      matchPercent: 80,
      status: "recommended",
      marketOutlookLabel: "High Growth (11% YoY)",
      marketOutlook: "up",
      salaryRange: "$95k – $145k",
      salaryTier: 3,
      educationRequired: "BS / MS Preferred",
      educationMatchesAnchor: true,
      keySynergy: "Behavioral insight synthesis and human-systems analysis align with empathic analytical profiles.",
      keyFriction: "User interview moderation requires sustained interpersonal facilitation skills.",
      pros: [
        "Bridges human behavior research with direct product design impact.",
        "Remote-first roles widely available at tech companies.",
        "Independent synthesis and report preparation are core deliverables.",
        "Strong demand as product teams prioritize evidence-based design.",
        "Research findings generate durable organizational value.",
      ],
      cons: [
        "Moderated user interview sessions require interpersonal facilitation.",
        "Advocacy for research findings requires cross-functional communication.",
      ],
    },
    {
      id: "rs5-r5",
      title: "Behavioral Economist / Policy Advisor",
      sector: "Economics / Public Sector",
      domain: "Law",
      matchPercent: 76,
      status: "recommended",
      marketOutlookLabel: "Growing (7% YoY)",
      marketOutlook: "up",
      salaryRange: "$80k – $130k",
      salaryTier: 3,
      educationRequired: "MS / PhD Preferred",
      educationMatchesAnchor: false,
      keySynergy: "Applying behavioral science to institutional design rewards analytical and strategic depth.",
      keyFriction: "Government and institutional environments move slowly against fast-thinking profiles.",
      pros: [
        "Research-based policy recommendations have broad societal impact.",
        "Independent analytical modeling and report preparation.",
        "Published research builds lasting intellectual and professional authority.",
        "Remote-compatible for research and writing phases.",
        "Highly interdisciplinary work prevents intellectual stagnation.",
      ],
      cons: [
        "Institutional bureaucracy significantly slows implementation cycles.",
        "PhD increasingly expected for senior advisory positions.",
      ],
    },
    {
      id: "rs5-f1",
      title: "Elementary School Principal",
      sector: "Education Administration",
      domain: "Education",
      matchPercent: 11,
      status: "flagged",
      marketOutlookLabel: "Stable (2% YoY)",
      marketOutlook: "flat",
      salaryRange: "$80k – $110k",
      salaryTier: 2,
      educationRequired: "MA + Administrative License",
      educationMatchesAnchor: true,
      keySynergy: "Organizational structure planning has some analytical alignment.",
      keyFriction: "Constant parent, staff, and student management in a loud, in-person-only environment.",
      flagReason: "School administration demands constant high-volume interpersonal management, crisis escalation, and full in-person presence — incompatible with introversion and remote preference.",
      pros: ["Institutional systems design has organizational structure components."],
      cons: [
        "Constant parent, student, and staff management throughout every day.",
        "100% in-person — remote work unavailable in any district.",
        "Emotional labor intensity is extremely high.",
        "Limited analytical independence — role is primarily reactive.",
      ],
    },
    {
      id: "rs5-f2",
      title: "Personal Fitness Trainer",
      sector: "Wellness",
      domain: "Medical",
      matchPercent: 7,
      status: "flagged",
      marketOutlookLabel: "Moderate Growth (5% YoY)",
      marketOutlook: "up",
      salaryRange: "$35k – $65k",
      salaryTier: 1,
      educationRequired: "Certification Required",
      educationMatchesAnchor: true,
      keySynergy: "Program design has structured planning components.",
      keyFriction: "100% in-person physical contact, motivation facilitation, and client relationship management.",
      flagReason: "Role is entirely in-person, physical, and relationship-dependent. Daily one-on-one client motivation and emotional support are the core job function — incompatible with introversion, remote preference, and analytical work style.",
      pros: ["Periodization program design has structured planning components."],
      cons: [
        "100% in-person physical client interaction.",
        "Income highly variable and client-retention dependent.",
        "Emotional motivator role drains introverted energy reserves rapidly.",
        "Severe credential underutilization relative to education anchor.",
      ],
    },
    {
      id: "rs5-f3",
      title: "Bartender / Bar Manager",
      sector: "Hospitality",
      domain: "Creative Arts",
      matchPercent: 5,
      status: "flagged",
      marketOutlookLabel: "Stable (3% YoY)",
      marketOutlook: "flat",
      salaryRange: "$30k – $55k",
      salaryTier: 1,
      educationRequired: "HS Diploma",
      educationMatchesAnchor: true,
      keySynergy: "None of significance.",
      keyFriction: "High-volume social interaction, late-night shifts, and noisy in-person environment are the full job description.",
      flagReason: "Every aspect of this role — social atmosphere, shift hours, in-person requirement, and relationship-based income — directly conflicts with introversion, remote preference, analytical work style, and education-level anchoring.",
      pros: ["None identified for this profile."],
      cons: [
        "Constant high-volume social interaction is the entire job.",
        "Entirely in-person with late-night irregular scheduling.",
        "Severe credential underutilization for any educated professional.",
        "Income depends entirely on interpersonal rapport with strangers.",
      ],
    },
    {
      id: "rs5-f4",
      title: "Motivational Speaker",
      sector: "Entertainment / Training",
      domain: "Creative Arts",
      matchPercent: 9,
      status: "flagged",
      marketOutlookLabel: "Volatile",
      marketOutlook: "flat",
      salaryRange: "$30k – $300k+ (highly variable)",
      salaryTier: 2,
      educationRequired: "None Required",
      educationMatchesAnchor: true,
      keySynergy: "Communication of complex ideas has some alignment with analytical profiles.",
      keyFriction: "Public performance, constant travel, and extroversion-dependent success are the core role requirements.",
      flagReason: "Career success is 100% dependent on public performance charisma, high-extroversion presence, and constant travel — directly opposing introversion, remote preference, and preference for analytical independent work.",
      pros: ["Complex idea communication aligns with deep knowledge strengths."],
      cons: [
        "Success entirely dependent on stage charisma and extroversion.",
        "Constant travel and in-person engagements required.",
        "Income extremely volatile with no floor guarantee.",
        "Role requires perpetual self-promotion and public visibility.",
      ],
    },
    {
      id: "rs5-f5",
      title: "Door-to-Door Salesperson",
      sector: "Sales",
      domain: "Business",
      matchPercent: 1,
      status: "flagged",
      marketOutlookLabel: "Rapidly Declining (−10% YoY)",
      marketOutlook: "down",
      salaryRange: "$25k – $60k",
      salaryTier: 1,
      educationRequired: "HS Diploma",
      educationMatchesAnchor: true,
      keySynergy: "None identified.",
      keyFriction: "Physical canvassing, constant rejection, and outdoor in-person work are the entire role.",
      flagReason: "Complete mismatch across every dimension. Physical door-to-door canvassing, constant in-person rejection, and outdoor work directly conflict with remote preference, introversion, indoor analytical work preference, and education-level anchoring.",
      pros: ["None identified for this profile."],
      cons: [
        "Constant in-person cold-call rejection throughout every day.",
        "Outdoor physical canvassing in all weather conditions.",
        "Structurally collapsing industry with no meaningful future.",
        "Complete credential and education underutilization.",
      ],
    },
  ],
};

// ── All Result Sets ────────────────────────────────────────────────────────────

export const ALL_RESULT_SETS: ResultSet[] = [
  resultSet1,
  resultSet2,
  resultSet3,
  resultSet4,
  resultSet5,
];

export function getRandomResultSet(): ResultSet {
  return ALL_RESULT_SETS[Math.floor(Math.random() * ALL_RESULT_SETS.length)];
}

// ── Domains for filter ─────────────────────────────────────────────────────────

export const CAREER_DOMAINS = [
  "All Domains",
  "Technology",
  "Finance",
  "Medical",
  "Law",
  "Business",
  "Creative Arts",
  "Education",
] as const;

export type CareerDomain = (typeof CAREER_DOMAINS)[number];

// ── Legacy types kept for sidebar MBTI picker compatibility ───────────────────

export type MarketOutlookType = MarketOutlook;

export interface MbtiProfile {
  type: string;
  nickname: string;
  confidencePercent: number;
  activeVariables: string;
  careers: CareerMatch[];
}

export const mbtiOptions = [
  { type: "INTJ", label: "INTJ (Architect)" },
  { type: "INFJ", label: "INFJ (Advocate)" },
  { type: "ENFP", label: "ENFP (Campaigner)" },
  { type: "ENTP", label: "ENTP (Debater)" },
  { type: "ISTJ", label: "ISTJ (Logistician)" },
  { type: "ENTJ", label: "ENTJ (Commander)" },
];

export function getProfile(type: string): MbtiProfile {
  return {
    type,
    nickname: mbtiOptions.find((o) => o.type === type)?.label.split(" ")[1]?.replace(/[()]/g, "") ?? type,
    confidencePercent: 85,
    activeVariables: `${type}-A, Remote preference, and 4 active variables`,
    careers: [],
  };
}

export function salaryTierGlyphs(tier: CareerMatch["salaryTier"]): string {
  return "$".repeat(tier);
}
